### ISSUE TITLE
Issue in ssl

### ISSUE THREAD

**Issue by riteshghimire9090** [jmshamran/easydaraz#1]

**Comment by jmshamran** [comment]
can you eloborate?

**Comment by riteshghimire9090** [comment]
Fatal  error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60:  SSL certificate problem: unable to get local issuer certificate (see  https://curl.haxx.se/libcurl/c/libcurl-errors.html) in  C:\Users\User\Local  Sites\shop\app\public\wp-content\plugins\daraz\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php  on line 208
--

**Use with Wordpress**

**Comment by jmshamran** [comment]
It is unsecure to set Guzzle SSL verification to false. You can set it to false on your end using this Guzzle code from the documentation [here](http://docs.guzzlephp.org/en/latest/request-options.html#verify).
You can see a related issue [here](https://github.com/guzzle/guzzle/issues/394).

**Comment by riteshghimire9090** [comment]
Thanks for Your contribution!

**Comment by riteshghimire9090** [comment]
$url = $this->url . '?' . $queryString;
        $client->setDefaultOption('verify', false);
        $response = $client->request('GET', 'https://ocean.ac-guadeloupe.fr/publinet/resultats');

same issue

**Comment by jmshamran** [comment]
try setting it to false in the getRequest function.
`$response = $client->request('GET', $url,['verify' => false]);`
The issue is related to website SSL problem, It will work fine in a localhost or a website with a proper SSL certificate.

**Comment by riteshghimire9090** [comment]
ok

**Comment by jmshamran** [comment]
Thanks for the feedback :)

**Comment by riteshghimire9090** [comment]
[](url)
![Capture](https://user-images.githubusercontent.com/38576994/87883075-79d72e00-ca24-11ea-9fe3-5a4ac9eea2ca.PNG)
![Capture1](https://user-images.githubusercontent.com/38576994/87883076-7ba0f180-ca24-11ea-800a-ba7dd9b50ba5.PNG)

same issue can u please help me out bro!

**Comment by riteshghimire9090** [comment]
its fine while working in testing file but not in wordpress!

**Comment by jmshamran** [comment]
Setting SSL verification to 'false' is for testing purpose only. WordPress needs proper SSL confirmation.
can you show me your code? point out the places you modifed?
